version: "3.9"
services:
  doubt-backend:
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo-doubt
  mongo-doubt:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=paiva
      - MONGO_INITDB_ROOT_PASSWORD=contrasenia
