GET http://localhost:8000/api/clothes 

###

POST http://localhost:8000/api/clothes 
Content-Type: application/json

{
    "id": 0,
    "type": "pant",
    "sizes": ["s","m","l"],
    "img_front":"foto frente!",
    "img_back":"foto detras!"
}